### ISSUE TITLE
Chart fails on Openshift: root image

### ISSUE THREAD

**Issue by andrescolodrero** [OctopusDeploy/helm-charts#2]
HI,
i get this error deploying octopus on Openshift.
is it possible to run Octopus Deploy on rootless containers?

Error: container create failed: time="2023-03-07T12:12:28Z" level=error msg="runc create failed: unable to start container process: exec ./install.sh: permission denied"

**Comment by MJRichardson** [comment]
Hey Andres, 

Recent versions of the Octopus image can't be run rootless.  [It seems we may have inadvertently introduced this recently](https://help.octopus.com/t/attempting-to-run-rootless-dockerd-but-missing-necessary-entries-in-etc-subuid/28764/5).

I'll leave this issue open and see if we can get this resolved.

**Comment by artursp** [comment]
Should be resolved with https://github.com/OctopusDeploy/helm-charts/pull/4

**Comment by andrescolodrero** [comment]
resolved
