### ISSUE TITLE
Azure Stack HCI Support

### ISSUE THREAD

**Issue by gavinwilliams** [OctopusDeploy/helm-charts#224]
We're trying to deploy the agent to a K8s cluster behind Azure Stack HCI. We're having issues with PV's, specifically the driver required for NFS on Azure Stack HCI isn't nfs.csi.k8s.io but nfs.csi.akshci.com.

It would be great if we could have this as a configurable option in the values file.

**Comment by APErebus** [comment]
Hi @gavinwilliams,

Did you install the NFS CSI driver? That's what installs the `nfs.csi.k8s.io` driver.

If you want to use the `nfs.csi.akshci.com` driver, you'll need to [create](https://kubernetes.io/docs/concepts/storage/storage-classes/) a custom `StorageClass` (or find the default storage class for this driver), then provide that StorageClass name as part of the Kubernetes agent install UI or via these helm values:

`persistence.storageClassName` and then set `persistence.nfs.enabled` to `false`

**Comment by gavinwilliams** [comment]
> Hi @gavinwilliams,
> 
> 
> 
> Did you install the NFS CSI driver? That's what installs the `nfs.csi.k8s.io` driver.
> 
> 
> 
> If you want to use the `nfs.csi.akshci.com` driver, you'll need to [create](https://kubernetes.io/docs/concepts/storage/storage-classes/) a custom `StorageClass` (or find the default storage class for this driver), then provide that StorageClass name as part of the Kubernetes agent install UI or via this helm value `persistence.storageClassName`
> 
> 
> 
> 

I did, unfortunately I consistently ran into errors with the pod starting, I believe the error related to having unbound PV claims.

**Comment by APErebus** [comment]
> I did, unfortunately I consistently ran into errors with the pod starting, I believe the error related to having unbound PV claims specifically with the nfs.csi.k8s.io driver.

You will see that temporarily as the NFS pod starts up, but once the NFS pod starts, it should bind the PV claim to the tentacle pod.
