### ISSUE TITLE
Insecure Dependency-npm package braces

### ISSUE THREAD

**Issue by jimh-datacom** [OctopusDeploy/helm-charts#269]
Dependabot has picked out a weakness in the **braces** package.

The package **braces** fails to limit the number of characters it can handle, which could lead to Memory Exhaustion

To resolve the issue, upgrade **braces** to version **3.0.3 or later**.

**Comment by APErebus** [comment]
@jimh-datacom Thank you for the report.

We only use NPM packages for CI/CD purposes and it's not part of the released packages. We'll look to update this

**Comment by APErebus** [comment]
This has been fixed with #278
