### ISSUE TITLE
Helm install of ocotpus server fails if trying to set masterKey through values

### ISSUE THREAD

**Issue by johatl** [OctopusDeploy/helm-charts#305]
When running the helm deployment with masterKey set, the deployment fails:

`helm upgrade --install --atomic --set octopus.masterKey='*************' --set octopus.databaseConnectionString='dummy' octopus oci://ghcr.io/octopusdeploy/octopusdeploy-helm 
Release "octopus" does not exist. Installing it now.
Pulled: ghcr.io/octopusdeploy/octopusdeploy-helm:1.0.0
Digest: sha256:5510a6b80c0342fb088d4f04140018bdec550bdf177106b73863c126e83dbe77
Error: template: octopusdeploy-helm/templates/NOTES.txt:10:42: executing "octopusdeploy-helm/templates/NOTES.txt" at <or>: wrong number of args for or: want at least 1 got 0`

**Comment by APErebus** [comment]
@liam-mackie Can this issue be closed now?
